version: '3.7'
services:
  web:
    image: webdevops/php-nginx-dev:7.4
    environment:
      WEB_DOCUMENT_ROOT: '/app/public'
      WEB_ALIAS_DOMAIN: 'testmenu'
      XDEBUG_REMOTE_CONNECT_BACK: 1
      XDEBUG_REMOTE_PORT: 9001
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    container_name: testmenu

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testmenu
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  composer:
    image: composer:1.10.7
    working_dir: /app
    volumes:
      - .:/app
